"""
Is this file ours? (R-36)

Given an audio or video file, and optionally its manifest, report what evidence of this platform's
origin it carries. Three independent kinds of evidence are checked and reported separately, because
they fail in different ways:

* the **invisible watermarks**: the audio mark in the sound (a video's soundtrack counts), the video
  mark in the frames. These survive re-encoding, trimming and mild noise, but a determined edit can
  remove them.
* the **signed manifest**: unforgeable without the key and bound to one exact file by its SHA-256,
  but it is a separate file that can simply be lost or stripped, and any re-encode changes the hash.
* the **audit record**: the entry written when the manifest was issued, found by the manifest id the
  video watermark carries (nearest match, so a compressed copy that reads the id with a few bit errors
  still finds it).

The verdict combines them, and states what it does *not* show. In particular a file with no marks
**proves nothing**: it may be genuine footage, it may be generated by something else, or one of ours
whose marks were removed. This module can say "this came from here"; it cannot say "this did not".
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

import audit_log
import manifest as manifest_module
import video_io
import video_watermark
import watermark_engine

logger = logging.getLogger(__name__)

VERDICTS = {
    "authentic_original": "This is the exact file this platform issued: its signed manifest is valid and matches the file's hash.",
    "ours_modified": "This was made by this platform (its watermark is present) but is not the file the manifest was issued for: it has been re-encoded, edited, trimmed or its manifest is missing.",
    "manifest_for_another_file": "A valid manifest from this platform was supplied, but it was issued for a different file, and this file carries no watermark of ours.",
    "tampered_manifest": "The manifest does not match its own signature: it was edited after it was issued.",
    "foreign_manifest": "The manifest is validly signed, but by a different key than this platform's: it was issued somewhere else.",
    "no_evidence": "No evidence of this platform's origin was found. This does NOT show the content is real: it may be authentic footage, generated elsewhere, or ours with the marks removed.",
}

LIMITS = (
    "Watermarks survive re-encoding, trimming and moderate noise but not every edit (heavy compression, strong "
    "cropping, re-synthesis, speed changes). A manifest proves origin only for the exact bytes it names. "
    "Nothing here detects fakes made by other systems."
)


def _file_facts(path: Path, info: Any) -> Dict[str, Any]:
    return {
        "name": path.name,
        "bytes": path.stat().st_size,
        "sha256": manifest_module.sha256_file(path),
        "kind": "video" if info.has_video else "audio",
        "durationSeconds": round(float(info.video_duration or info.audio_duration or 0.0), 3),
    }


def _video_mark(path: Path) -> Dict[str, Any]:
    try:
        return video_watermark.shared_video_watermarker().detect_video(path, sample_frames=24).to_dict()
    except video_watermark.VideoWatermarkUnavailable as err:
        return {"available": False, "detected": False, "reason": str(err)}


def _audio_mark(path: Path, info: Any) -> Dict[str, Any]:
    # ffmpeg decodes anything (WAV, MP3, AAC in .m4a, a video's soundtrack); soundfile cannot open AAC.
    try:
        audio = video_io.read_audio(path, 16000)
        return watermark_engine.shared_watermarker().detect(audio, 16000).to_dict()
    except watermark_engine.WatermarkUnavailable as err:
        return {"available": False, "detected": False, "reason": str(err)}


def verify_file(path: Path | str, manifest_document: Optional[Dict[str, Any]] = None, name: Optional[str] = None) -> Dict[str, Any]:
    """
    Examine one file. ``manifest_document`` is a parsed manifest; when absent, ``<file>.manifest.json``
    beside the file is used if it exists. ``name`` is what to call the file in the report (an upload's own
    filename, not the temporary one). Raises ``ValueError`` if the file is not readable media.
    """
    path = Path(path)
    shown = name or path.name
    try:
        info = video_io.probe(path)
    except Exception as err:  # noqa: BLE001 - ffprobe's message is the useful part
        # ffprobe quotes the path it was given; the caller sees the file's own name, never ours.
        raise ValueError(f"{shown} is not audio or video this server can read ({str(err).replace(str(path), shown).replace(path.name, shown)})") from err
    if not (info.has_video or info.has_audio):
        raise ValueError(f"{shown} contains neither a video nor an audio stream")

    facts = _file_facts(path, info)
    facts["name"] = shown
    explanation: List[str] = []

    watermarks: Dict[str, Optional[Dict[str, Any]]] = {"video": None, "audio": None}
    if info.has_video:
        watermarks["video"] = _video_mark(path)
    if info.has_audio:
        watermarks["audio"] = _audio_mark(path, info)
    watermark_found = any(w and w.get("detected") for w in watermarks.values())

    sidecar = Path(str(path) + ".manifest.json")
    source = "supplied"
    if manifest_document is None and sidecar.is_file():
        import json

        try:
            manifest_document, source = json.loads(sidecar.read_text()), "sidecar"
        except ValueError:
            explanation.append("a manifest file sits beside the video but is not valid JSON")
    manifest_report = manifest_module.verify(manifest_document, path).to_dict() if manifest_document is not None else None
    if manifest_report:
        manifest_report["source"] = source

    # The audit record: from the id in the video mark (nearest match), else from the manifest's own id.
    record = None
    trail = audit_log.shared_audit()
    mark_id = (watermarks["video"] or {}).get("manifestId")
    for candidate in (mark_id, (manifest_document or {}).get("manifestId") if isinstance(manifest_document, dict) else None):
        if candidate:
            record = trail.find_manifest(candidate)
            if record:
                break

    # ---- the verdict
    if manifest_report and manifest_report["trustworthy"]:
        verdict = "authentic_original"
    elif manifest_report and not manifest_report["validSignature"]:
        verdict = "tampered_manifest"
    elif manifest_report and manifest_report["validSignature"] and not manifest_report["issuedByUs"]:
        verdict = "foreign_manifest"
    elif watermark_found:
        verdict = "ours_modified"
    elif manifest_report and manifest_report["validSignature"] and manifest_report["issuedByUs"]:
        verdict = "manifest_for_another_file"
    else:
        verdict = "no_evidence"

    if watermark_found:
        which = [k for k, w in watermarks.items() if w and w.get("detected")]
        explanation.append(f"this platform's invisible watermark was found in the {' and '.join(which)}")
    if record:
        details = record["details"]
        explanation.append(
            f"the video's watermark traces to a manifest issued {record['ts']} for job {details.get('job')!r}"
            f" (id read with {record['bitErrors']} bit error(s))"
        )
        if details.get("video_sha256") and details["video_sha256"] != facts["sha256"]:
            explanation.append("the issued video's hash differs from this file's, so this is a modified copy")
    for problem in (manifest_report or {}).get("problems", []):
        explanation.append(problem)
    if verdict == "no_evidence" and (watermarks["video"] or {}).get("available") is False:
        explanation.append("the video watermark model is not installed here, so the frames could not be checked")

    return {
        "file": facts,
        "verdict": verdict,
        "meaning": VERDICTS[verdict],
        "watermarks": watermarks,
        "manifest": manifest_report,
        "record": record,
        "explanation": explanation,
        "limits": LIMITS,
    }
