"""
Is this file ours? (R-36)

Given an audio or video file, and optionally its manifest, report what evidence of this platform's
origin it carries. Three independent kinds of evidence are checked and reported separately, because
they fail in different ways:

* the **invisible watermarks**: the audio mark in the sound (a video's soundtrack counts), the video
  mark in the frames. These survive re-encoding, trimming and mild noise, but a determined edit can
  remove them.
* the **signed manifest**: unforgeable without the key and bound to one exact file by its SHA-256,
  but it is a separate file that can simply be lost or stripped, and any re-encode changes the hash.
* the **audit record**: the entry written when the manifest was issued, found by the manifest id the
  video watermark carries (nearest match, so a compressed copy that reads the id with a few bit errors
  still finds it).

The verdict combines them, and states what it does *not* show. In particular a file with no marks
**proves nothing**: it may be genuine footage, it may be generated by something else, or one of ours
whose marks were removed. This module can say "this came from here"; it cannot say "this did not".

Where it sits: this is the read side of the provenance pipeline. The write side (``watermark_engine``,
``video_watermark``, ``manifest``, ``audit_log``) runs when a render finishes; this module runs when
someone uploads a file to ``POST /verify`` in ``app.py`` and asks "did this come from here?".

Concepts used below, explained once:

**SHA-256** is a cryptographic hash: a 64-hex-character fingerprint of a file's exact bytes. Change
one byte and the fingerprint changes completely, which is why the manifest can name "this exact file"
and also why any re-encode breaks the match.

**A signature** (Ed25519 here, checked in ``manifest.verify``) proves two things: the manifest was not
edited after signing, and it was signed by the holder of a particular private key. "Valid" and "ours"
are separate questions: a stranger can produce a validly signed manifest with their own key.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

import audit_log
import manifest as manifest_module
import video_io
import video_watermark
import watermark_engine

logger = logging.getLogger(__name__)

# The fixed vocabulary of outcomes. The API returns the key; the frontend shows the sentence. Keeping
# both in one dict means a new verdict cannot be added without its plain-language meaning.
VERDICTS = {
    "authentic_original": "This is the exact file this platform issued: its signed manifest is valid and matches the file's hash.",
    "ours_modified": "This was made by this platform (its watermark is present) but is not the file the manifest was issued for: it has been re-encoded, edited, trimmed or its manifest is missing.",
    "manifest_for_another_file": "A valid manifest from this platform was supplied, but it was issued for a different file, and this file carries no watermark of ours.",
    "tampered_manifest": "The manifest does not match its own signature: it was edited after it was issued.",
    "foreign_manifest": "The manifest is validly signed, but by a different key than this platform's: it was issued somewhere else.",
    "no_evidence": "No evidence of this platform's origin was found. This does NOT show the content is real: it may be authentic footage, generated elsewhere, or ours with the marks removed.",
}

# Returned with every report so a caller can never show a verdict without its caveats (golden rule 8:
# say what is not done). The adjacent string literals are joined by Python into one string.
LIMITS = (
    "Watermarks survive re-encoding, trimming and moderate noise but not every edit (heavy compression, strong "
    "cropping, re-synthesis, speed changes). A manifest proves origin only for the exact bytes it names. "
    "Nothing here detects fakes made by other systems."
)


def _file_facts(path: Path, info: Any) -> Dict[str, Any]:
    """
    Describe the file itself: name, size, SHA-256, kind and duration.

    ``info`` is the ``video_io.probe`` result. A file with any video stream is reported as video even
    when it also has sound. Duration prefers the video stream's and falls back to the audio's.
    """
    return {
        "name": path.name,
        "bytes": path.stat().st_size,
        "sha256": manifest_module.sha256_file(path),
        "kind": "video" if info.has_video else "audio",
        "durationSeconds": round(float(info.video_duration or info.audio_duration or 0.0), 3),
    }


def _video_mark(path: Path) -> Dict[str, Any]:
    """
    Read the invisible video watermark from frames sampled through the file.

    Returns the detector's report as a dict. When the watermark model is not installed it returns an
    ``available: False`` report with the reason instead of raising, so the rest of the check still runs
    and the missing model is visible in the result (golden rule 1: no silent fallbacks).
    """
    # 24 sampled frames rather than the module default of 48: half the decode work per upload. Which
    # count gives the best speed/robustness trade-off is not recorded here.
    try:
        return video_watermark.shared_video_watermarker().detect_video(path, sample_frames=24).to_dict()
    except video_watermark.VideoWatermarkUnavailable as err:
        return {"available": False, "detected": False, "reason": str(err)}


def _audio_mark(path: Path, info: Any) -> Dict[str, Any]:
    """
    Read the invisible AudioSeal watermark from the file's sound.

    Like ``_video_mark``, a missing model becomes an ``available: False`` report rather than an error.
    ``info`` is accepted for symmetry with ``_file_facts`` but not used.
    """
    # ffmpeg decodes anything (WAV, MP3, AAC in .m4a, a video's soundtrack); soundfile cannot open AAC.
    try:
        # 16 kHz because that is AudioSeal's working rate (``watermark_engine.MODEL_RATE``).
        audio = video_io.read_audio(path, 16000)
        return watermark_engine.shared_watermarker().detect(audio, 16000).to_dict()
    except watermark_engine.WatermarkUnavailable as err:
        return {"available": False, "detected": False, "reason": str(err)}


def verify_file(path: Path | str, manifest_document: Optional[Dict[str, Any]] = None, name: Optional[str] = None) -> Dict[str, Any]:
    """
    Examine one file. ``manifest_document`` is a parsed manifest; when absent, ``<file>.manifest.json``
    beside the file is used if it exists. ``name`` is what to call the file in the report (an upload's own
    filename, not the temporary one). Raises ``ValueError`` if the file is not readable media.
    """
    # Accept str or Path from callers, but work with a Path internally.
    path = Path(path)
    shown = name or path.name
    try:
        info = video_io.probe(path)
    except Exception as err:  # noqa: BLE001 - ffprobe's message is the useful part
        # ffprobe quotes the path it was given; the caller sees the file's own name, never ours.
        raise ValueError(f"{shown} is not audio or video this server can read ({str(err).replace(str(path), shown).replace(path.name, shown)})") from err
    if not (info.has_video or info.has_audio):
        raise ValueError(f"{shown} contains neither a video nor an audio stream")

    facts = _file_facts(path, info)
    # Report the uploader's filename, not the server's temporary one, which would leak a server path.
    facts["name"] = shown
    explanation: List[str] = []

    # None means "this file has no such stream", which is different from "checked and not found".
    watermarks: Dict[str, Optional[Dict[str, Any]]] = {"video": None, "audio": None}
    if info.has_video:
        watermarks["video"] = _video_mark(path)
    if info.has_audio:
        watermarks["audio"] = _audio_mark(path, info)
    # Either mark is enough: a video whose soundtrack was replaced can still carry the frame mark.
    watermark_found = any(w and w.get("detected") for w in watermarks.values())

    # A "sidecar" is a companion file stored next to the main one: render.mp4 -> render.mp4.manifest.json.
    # A manifest the caller uploaded wins; the sidecar is only the fallback.
    sidecar = Path(str(path) + ".manifest.json")
    source = "supplied"
    if manifest_document is None and sidecar.is_file():
        import json

        try:
            manifest_document, source = json.loads(sidecar.read_text()), "sidecar"
        except ValueError:
            # json.JSONDecodeError is a subclass of ValueError. A broken sidecar is reported, not fatal.
            explanation.append("a manifest file sits beside the video but is not valid JSON")
    manifest_report = manifest_module.verify(manifest_document, path).to_dict() if manifest_document is not None else None
    if manifest_report:
        # Say where the manifest came from, so a reader knows whether the uploader supplied it.
        manifest_report["source"] = source

    # The audit record: from the id in the video mark (nearest match), else from the manifest's own id.
    # The watermark's id is tried first because it travels inside the file and survives losing the
    # manifest; the manifest's own id is the second chance. ``find_manifest`` tolerates bit errors.
    record = None
    trail = audit_log.shared_audit()
    mark_id = (watermarks["video"] or {}).get("manifestId")
    for candidate in (mark_id, (manifest_document or {}).get("manifestId") if isinstance(manifest_document, dict) else None):
        if candidate:
            record = trail.find_manifest(candidate)
            if record:
                break

    # ---- the verdict
    # Order matters: the first branch that holds wins. A trustworthy manifest is the strongest evidence,
    # so it is checked first; manifest problems come next because they are specific and actionable; the
    # watermark alone only says "ours, but changed"; a valid manifest of ours with no mark and no hash
    # match means the manifest belongs to some other file. "trustworthy" is valid AND ours AND matches.
    if manifest_report and manifest_report["trustworthy"]:
        verdict = "authentic_original"
    elif manifest_report and not manifest_report["validSignature"]:
        verdict = "tampered_manifest"
    elif manifest_report and manifest_report["validSignature"] and not manifest_report["issuedByUs"]:
        verdict = "foreign_manifest"
    elif watermark_found:
        verdict = "ours_modified"
    elif manifest_report and manifest_report["validSignature"] and manifest_report["issuedByUs"]:
        verdict = "manifest_for_another_file"
    else:
        verdict = "no_evidence"

    # The explanation list is plain sentences a person can read, built from every piece of evidence,
    # whatever the verdict was.
    if watermark_found:
        which = [k for k, w in watermarks.items() if w and w.get("detected")]
        explanation.append(f"this platform's invisible watermark was found in the {' and '.join(which)}")
    if record:
        details = record["details"]
        explanation.append(
            f"the video's watermark traces to a manifest issued {record['ts']} for job {details.get('job')!r}"
            f" (id read with {record['bitErrors']} bit error(s))"
        )
        # The audit entry recorded the hash of the file as issued; a different hash here means a copy.
        if details.get("video_sha256") and details["video_sha256"] != facts["sha256"]:
            explanation.append("the issued video's hash differs from this file's, so this is a modified copy")
    for problem in (manifest_report or {}).get("problems", []):
        explanation.append(problem)
    # "is False" rather than "not ...": a missing key (None) must not be read as "model not installed".
    if verdict == "no_evidence" and (watermarks["video"] or {}).get("available") is False:
        explanation.append("the video watermark model is not installed here, so the frames could not be checked")

    return {
        "file": facts,
        "verdict": verdict,
        "meaning": VERDICTS[verdict],
        "watermarks": watermarks,
        "manifest": manifest_report,
        "record": record,
        "explanation": explanation,
        "limits": LIMITS,
    }
