"""
Voice reference provenance and consent records.

Two problems share one solution.

The benchmark reads ``inputs/`` and measures cloning similarity against
whatever it finds first. Nothing recorded *what* that clip was, so a reference
concatenated from our own Kokoro output would have been measured, scored
against the >85% threshold and written into ``docs/benchmarks/`` as acceptance
evidence. Synthetic speech is a flattering cloning target -- no room reverb,
no mic coloration, no breath noise -- so the number would have looked good and
meant nothing.

Roadmap Phase 5 separately asks Developer 1 for a "biometric voice consent
verification protocol", which needs a durable record of who a reference voice
belongs to and on what basis it may be cloned.

A sidecar ``<audio>.provenance.json`` answers both. ``SYNTHETIC`` references
stay usable for wiring up the pipeline; only a ``HUMAN`` clip with a recorded
consent basis is admissible as evidence for the threshold.

Face photos use the same sidecar. For a face the question that matters is not
"is this admissible evidence" but "may this be animated at all": a talking
avatar of a real person made without their consent is the harm this project
most needs to prevent. ``usability`` answers that, and the avatar store and
the renderer both refuse an image that fails it.

Concepts, explained once:

* A **sidecar** is a small file stored next to the file it describes, named
  after it (``voice.wav`` -> ``voice.wav.provenance.json``). It travels with
  the media when the folder is copied and needs no database.
* **Usable** and **admissible** are different questions. Usable: may this be
  cloned or animated at all? Admissible: may a number measured on it count as
  evidence for a published threshold (golden rule 2)? A synthetic clip is the
  first but never the second.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

# Appended to the full file name, extension included, so ``a.wav`` and ``a.mp3``
# in the same folder each get their own record.
PROVENANCE_SUFFIX = ".provenance.json"

# Where the audio came from.
HUMAN = "human"
SYNTHETIC = "synthetic"

# Consent bases we accept for a human reference. A public corpus carries its
# consent in its licence, which is why it needs no separate recording.
CONSENT_BASES = {
    "speaker-recorded",  # the speaker recorded it themselves for this project
    "written-consent",  # a third party consented in writing
    "open-licence",  # public corpus (LJSpeech, LibriSpeech, VCTK, ...)
}

# Consent bases for a human face. "subject-provided" is the face equivalent of
# "speaker-recorded": the person in the photo supplied it for this project.
FACE_CONSENT_BASES = {
    "subject-provided",
    "written-consent",
    "open-licence",
}


@dataclass
class VoiceProvenance:
    """What a reference clip is, and whether it may be cloned."""

    # HUMAN or SYNTHETIC. Anything else is treated as unknown and refused.
    source: str
    speaker: str = "unknown"
    licence: str = ""
    consent_basis: str = ""
    notes: str = ""
    # default_factory runs at construction, so each record gets its own timestamp;
    # a plain default would be evaluated once, when the class is defined.
    created: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(timespec="seconds")
    )
    # Free-form lineage: generator model, prompt and seed for a synthetic
    # image, or the parent avatar and the edits applied for a derived one.
    extra: Dict[str, object] = field(default_factory=dict)

    @property
    def is_synthetic(self) -> bool:
        """True when the media was generated by a model rather than recorded."""
        return self.source == SYNTHETIC

    def usability(self) -> tuple[bool, str]:
        """
        Whether this media may be used (cloned, animated) at all.

        Weaker than ``admissibility``: a synthetic voice or face depicts no
        real person, so it is usable for anything even though it can never
        back a published metric. A human one needs a recorded consent basis.
        """
        if self.source == SYNTHETIC:
            return True, "synthetic media; depicts no real person"
        if self.source != HUMAN:
            return False, f"unknown provenance source {self.source!r}"
        # Either list is accepted here: a face consent basis and a voice one both mean
        # the real person agreed to this use.
        accepted = CONSENT_BASES | FACE_CONSENT_BASES
        if self.consent_basis not in accepted:
            return False, (
                f"consent basis {self.consent_basis!r} is not one of {sorted(accepted)}"
            )
        return True, f"human subject, consent basis: {self.consent_basis}"

    def admissibility(self) -> tuple[bool, str]:
        """
        Whether this clip may back the assignment's cloning-similarity claim.

        Returns ``(admissible, reason)``. The reason is written into the
        benchmark report so a future reader can see why a number was or was
        not counted.
        """
        if self.source == SYNTHETIC:
            return False, (
                "reference is synthetic (TTS output), which is an artificially "
                "easy cloning target; usable for pipeline testing only"
            )
        if self.source != HUMAN:
            return False, f"unknown provenance source {self.source!r}"
        # Stricter than usability(): only the voice consent bases count, because the
        # claim being backed is about voice cloning.
        if self.consent_basis not in CONSENT_BASES:
            return False, (
                f"consent basis {self.consent_basis!r} is not one of "
                f"{sorted(CONSENT_BASES)}"
            )
        return True, f"human speech, consent basis: {self.consent_basis}"

    def to_dict(self) -> Dict[str, object]:
        """The camelCase JSON shape written to the sidecar file."""
        return {
            "source": self.source,
            "speaker": self.speaker,
            "licence": self.licence,
            "consentBasis": self.consent_basis,
            "notes": self.notes,
            "created": self.created,
            # ``extra`` is left out when empty, so plain records stay short.
            **({"extra": self.extra} if self.extra else {}),
        }

    @classmethod
    def from_dict(cls, raw: Dict[str, object]) -> "VoiceProvenance":
        """
        Rebuild a record from its sidecar JSON.

        Every field is coerced to ``str`` and missing ones take the defaults, so a
        hand-edited or older sidecar still loads instead of raising.
        """
        return cls(
            source=str(raw.get("source", "")),
            speaker=str(raw.get("speaker", "unknown")),
            licence=str(raw.get("licence", "")),
            consent_basis=str(raw.get("consentBasis", "")),
            notes=str(raw.get("notes", "")),
            created=str(raw.get("created", "")),
            extra=dict(raw.get("extra") or {}) if isinstance(raw.get("extra"), dict) else {},
        )


# The record is the same for a voice and a face; the older name stays because
# the benchmark and its tests import it.
MediaProvenance = VoiceProvenance


def sidecar_path(audio_path: Path | str) -> Path:
    """The provenance file that belongs beside ``audio_path``."""
    audio = Path(audio_path)
    return audio.with_name(audio.name + PROVENANCE_SUFFIX)


def load(audio_path: Path | str) -> Optional[VoiceProvenance]:
    """Read the sidecar, or ``None`` when the clip has no provenance record."""
    path = sidecar_path(audio_path)
    if not path.is_file():
        return None
    try:
        raw = json.loads(path.read_text())
    # An unreadable sidecar is treated as no record, which every caller then
    # refuses; it never silently counts as consent.
    except (ValueError, OSError, TypeError):  # ValueError covers bad JSON and bad UTF-8
        return None
    # A sidecar that parses but is not a record is no record at all.
    if not isinstance(raw, dict):
        return None
    return VoiceProvenance.from_dict(raw)


def write(
    audio_path: Path | str,
    source: str,
    speaker: str = "unknown",
    licence: str = "",
    consent_basis: str = "",
    notes: str = "",
    extra: Optional[Dict[str, object]] = None,
) -> Path:
    """Write a provenance sidecar beside ``audio_path`` and return its path."""
    # Only the two known sources may be written; a typo here would otherwise
    # create a record that every later check refuses.
    if source not in (HUMAN, SYNTHETIC):
        raise ValueError(f"source must be {HUMAN!r} or {SYNTHETIC!r}, got {source!r}")
    record = VoiceProvenance(
        source=source,
        speaker=speaker,
        licence=licence,
        consent_basis=consent_basis,
        notes=notes,
        extra=dict(extra or {}),
    )
    path = sidecar_path(audio_path)
    path.write_text(json.dumps(record.to_dict(), indent=2) + "\n")
    return path


def describe(audio_path: Path | str) -> Dict[str, object]:
    """
    Provenance projected for a report, including the admissibility decision.

    A clip with no record is not admissible: silence is not consent, and an
    unlabelled reference is exactly the ambiguity this module removes.
    """
    record = load(audio_path)
    if record is None:
        return {
            "hasRecord": False,
            "admissible": False,
            "reason": (
                f"no provenance record. Create "
                f"{sidecar_path(audio_path).name} describing the speaker and "
                f"consent basis before this clip backs any published metric."
            ),
        }
    admissible, reason = record.admissibility()
    return {
        "hasRecord": True,
        "admissible": admissible,
        "reason": reason,
        **record.to_dict(),
    }


def usability(media_path: Path | str) -> tuple[bool, str]:
    """
    Whether ``media_path`` may be used at all, and why (not).

    No record means no: an unlabelled face is exactly the case the consent
    rule exists for, and the reason names the fix.
    """
    record = load(media_path)
    if record is None:
        return False, (
            f"no provenance record ({sidecar_path(media_path).name} is missing). "
            "Register the image with scripts/make_avatar.py, which records who "
            "it depicts and on what basis it may be animated."
        )
    return record.usability()


def warnings_for(audio_path: Path | str) -> List[str]:
    # One line per problem, phrased for a report reader, not for code.
    """Human-readable warnings to surface next to a measurement."""
    info = describe(audio_path)
    if info["admissible"]:
        return []
    return [f"NOT acceptance evidence: {info['reason']}"]
